build(deps): bump jiff from 0.2.16 to 0.2.17 (#41516)
Bumps [jiff](https://github.com/BurntSushi/jiff) from 0.2.16 to 0.2.17.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/BurntSushi/jiff/blob/master/CHANGELOG.md">jiff's
changelog</a>.</em></p>
<blockquote>
<h1>0.2.17 (2025-12-24)</h1>
<p>This release contains binary size improvements to Jiff, more succinct
error
messages and some new minor APIs.</p>
<p>While Jiff 1.0 is overdue, I've been doing a lot of experimenting
with
improving Jiff's binary size and compile times. In particular, I want to
spend
time doing this before Jiff 1.0 so that we don't box ourselves into a
corner.
(For example, some binary size improvements may require minor API
breaking
changes.)</p>
<p>In this release, Jiff has switched to structured error handling
internally
in an effort to provide error predicates and also hopefully improve
binary
sizes and compile times. Overall this didn't have as big of an impact on
binary sizes or compile times as I was hoping. I did take this
opportunity to
make Jiff's error messages a bit more succinct. In many cases, this
involved
de-duplicating some aspects of error messages and omitting user provided
input
in the messages. If you feel like there is a significant decrease in
error
message quality that isn't easily amended by callers providing
additional
context themselves, please open an issue.</p>
<p>This release also updates Jiff's bundled copy of the [IANA Time Zone
Database]
to <code>2025c</code>. See the <a
href="https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/TAGXKYLMAQRZRFTERQ33CEKOW7KRJVAK/"><code>2025c</code>
release announcement</a> for more details.</p>
<p>Enhancements:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/412">#412</a>:
Add <code>Display</code>, <code>FromStr</code>, <code>Serialize</code>
and <code>Deserialize</code> trait implementations
for <code>jiff::civil::ISOWeekDate</code>. These all use the ISO 8601
week date format.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/418">#418</a>:
Add some basic predicates to <code>jiff::Error</code> for basic error
introspection.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/pull/453">#453</a>,
<a href="https://redirect.github.com/BurntSushi/jiff/pull/454">#454</a>:
Switch to structured error handling internally.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/pull/456">#456</a>,
<a href="https://redirect.github.com/BurntSushi/jiff/pull/457">#457</a>,
<a href="https://redirect.github.com/BurntSushi/jiff/pull/458">#458</a>:
Various improvements to binary size.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/BurntSushi/jiff/commit/3b6547c2b6a75b5cc7ef90a79d3257fd5f0a4503"><code>3b6547c</code></a>
0.2.17</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/876d7c7e7484f905466b7ce608796c322390c366"><code>876d7c7</code></a>
changelog: 0.2.17</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/edb7cd21422ae6b9131c447eb8685d77c55968ff"><code>edb7cd2</code></a>
deps: bump jiff-tzdb to 0.1.5</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/61dc9bd8aa1cec759a35983e2f5984f47e5d8bf7"><code>61dc9bd</code></a>
fmt: rename <code>Decimal</code> to <code>Integer</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/1467f47e36ea69c6db079df4e7233943225a348d"><code>1467f47</code></a>
fmt: get rid of <code>Decimal::end</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/5b27b22096a39e1b022ef362c17b777f41688600"><code>5b27b22</code></a>
fmt: simplify decimal formatter</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/4d2041567c2b98f9105444cd8e16f9cb616271b6"><code>4d20415</code></a>
binary-size: remove many uses of <code>write!</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/21f69521cdeba481b66ee8bf24bd065967363b04"><code>21f6952</code></a>
shared: remove escaping and UTF-8 routines from <code>shared</code>
module</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/a50f6797ce06f78e1071acb653c4abc0f024b2c7"><code>a50f679</code></a>
logging: small tweak to formatting</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/0392d43064e3b73ea84f84d2c5ae5bb2b46cdd6b"><code>0392d43</code></a>
error: add note about introspection</li>
<li>Additional commits viewable in <a
href="https://github.com/BurntSushi/jiff/compare/jiff-static-0.2.16...jiff-static-0.2.17">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jiff&package-manager=cargo&previous-version=0.2.16&new-version=0.2.17)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>