Document libglu1-mesa-dev dependency.
Missing this caused
  src/gpu/gl/unix/SkNativeGLContext_unix.cpp:10:20:
  fatal error: GL/glu.h: No such file or directory
on my new laptop.