Use `homebrew bundle` to avoid errors on upgrade available.
`homebrew install` could exit with errors like:

```
Error: cmake 3.12.4 is already installed
To upgrade to 3.13.0, run `brew upgrade cmake`
```

This solution is the one recommended in https://github.com/Homebrew/brew/issues/2491