build(deps): bump jiff from 0.2.13 to 0.2.14 (#37071)
Bumps [jiff](https://github.com/BurntSushi/jiff) from 0.2.13 to 0.2.14.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/BurntSushi/jiff/blob/master/CHANGELOG.md">jiff's
changelog</a>.</em></p>
<blockquote>
<h1>0.2.14 (2025-05-20)</h1>
<p>This release includes a smattering of bug fixes, and hopefully a
small
improvement to the time it takes to compile Jiff. Also, in this release,
when
<code>TZ</code> is set to a non-empty but invalid value, Jiff will
always fall back to
<code>Etc/Unknown</code> when using <code>TimeZone::system()</code>.
This differs from previous
behavior where Jiff would, in this case, attempt to read the system's
default
time zone. This change brings Jiff into consistency with existing Unix
tooling
like <code>date</code>, and is also arguably a better failure mode. That
is, when <code>TZ</code> is
set but invalid, we shouldn't silently fall back to the default system
time
zone, but instead do something that indicates something has potentially
gone
wrong.</p>
<p>Enhancements:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/364">#364</a>:
Jiff now falls back to <code>Etc/Unknown</code> for invalid
<code>TZ</code> values.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/pull/379">#379</a>:
Improve compilation times.</li>
</ul>
<p>Bug fixes:</p>
<ul>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/365">#365</a>:
Fixes a compile error in Jiff when only the
<code>tzdb-concatenated</code> feature was
enabled.</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/366">#366</a>:
Fixes slow initial <code>Zoned::now()</code> in environments where
<code>/usr/share/zoneinfo</code>
is on a very slow file system (like CI environments).</li>
<li><a
href="https://redirect.github.com/BurntSushi/jiff/issues/376">#376</a>:
Avoids searching for a tzdb at <code>/usr/share/zoneinfo</code> on
Windows.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/BurntSushi/jiff/commit/8105228403c45402a5f553a80044d6a64891a8ab"><code>8105228</code></a>
0.2.14</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/39b9903e06da398f9ab59aac522b30a9aa80bfde"><code>39b9903</code></a>
changelog: 0.2.14</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/c0cfb2390d6fbdf1163e8de33c6d5cf4e5be8d0e"><code>c0cfb23</code></a>
test: add another scratch test for printing some interesting spans</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/ca0697735b201085fac11ea46ad616ddba33442b"><code>ca06977</code></a>
error: try to reduce amount of codegen by forcefully unlining error
constructors</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/08abeadd090e1f309eaed9bd3efa5947073c8d1e"><code>08abead</code></a>
tz: fallback to <code>Etc/Unknown</code> when <code>TZ</code> is set to
an invalid value</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/e22013e9b9dc0b313292519c2596c926a8624f19"><code>e22013e</code></a>
tz: don't search for tzdb at /usr/share/zoneinfo</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/c5c232094ce739fff21e051160cb08c5cad14d77"><code>c5c2320</code></a>
ci: improve tzdb init times and tests</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/0f9fdf8ec8baa83cebae05b9fd483991cfc14bcd"><code>0f9fdf8</code></a>
tz: improve performance of initial <code>Zoned::now()</code></li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/4e4939d199838210f13d57703e231915e6e42320"><code>4e4939d</code></a>
jiff-icu: bump ICU4X to 2.0.0</li>
<li><a
href="https://github.com/BurntSushi/jiff/commit/e729efaea3206b14a5537f10d2423f85a5dd68e9"><code>e729efa</code></a>
jiff-icu: upgrade to ICU4X 2.0.0</li>
<li>Additional commits viewable in <a
href="https://github.com/BurntSushi/jiff/compare/jiff-static-0.2.13...jiff-static-0.2.14">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jiff&package-manager=cargo&previous-version=0.2.13&new-version=0.2.14)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>