build: Force using CMake to build `aws-lc-sys` for Android + Bump `aws-lc-rs` 1.15.2 -> 1.15.3 (#41912)
There is a significant change, which replaced the CMake build with a new
cc builder. This does not work for Android, so we force CMake for
Android only. This is fine as we already set up CMake toolchain for
Android.

Bumps [aws-lc-rs](https://github.com/aws/aws-lc-rs) from 1.15.2 to
1.15.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/aws/aws-lc-rs/releases">aws-lc-rs's
releases</a>.</em></p>
<blockquote>
<h2>aws-lc-rs v1.15.3</h2>
<h2>What's Changed</h2>
<ul>
<li>🎉 CMake no longer required for any targets 🎉 by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/911">aws/aws-lc-rs#911</a>
<ul>
<li>For non-FIPS builds on all platforms only a C compiler is
required!</li>
</ul>
</li>
<li>impl Send for Streaming Keys by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/977">aws/aws-lc-rs#977</a></li>
<li><code>less_safe_update</code> for Streaming ciphers by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/991">aws/aws-lc-rs#991</a></li>
<li>aws-lc-fips-sys v0.13.11 aligns with <a
href="https://github.com/aws/aws-lc/releases/tag/AWS-LC-FIPS-3.1.0">AWS-LC-FIPS-3.1.0</a>
by <a href="https://github.com/justsmth"><code>@​justsmth</code></a> in
<a
href="https://redirect.github.com/aws/aws-lc-rs/pull/994">aws/aws-lc-rs#994</a></li>
</ul>
<h3>Build Improvements</h3>
<ul>
<li>Add support for i686-win7-windows target by <a
href="https://github.com/cstkingkey"><code>@​cstkingkey</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/988">aws/aws-lc-rs#988</a></li>
<li>Support mips &amp; rustc_codegen_cranelift compiler backend by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/986">aws/aws-lc-rs#986</a></li>
<li>Fix path formatting for build flags in cc_builder by <a
href="https://github.com/roobscoob"><code>@​roobscoob</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/989">aws/aws-lc-rs#989</a></li>
<li><code>disable-prebuilt-nasm</code> feature by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/997">aws/aws-lc-rs#997</a></li>
</ul>
<h3>Issues Being Closed</h3>
<ul>
<li>Disabling pre-built nasm binaries through feature flags
(aws-lc-rs/disable-prebuilt-nasm) -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/996">#996</a></li>
<li>StreamingDecryptingKey and StreamingEncryptingKey need useless extra
block in output -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/990">#990</a></li>
<li>build failure when targeting mips64el-unknown-linux-gnuabi64 or
i686-win7-windows-msvc -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/982">#982</a></li>
<li>build failure when targeting x86_64-pc-windows-msvc -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/981">#981</a></li>
<li>aws-lc-sys on ppc64le: undefined reference to
aws_lc_0_35_0_aes_hw_encrypt -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/980">#980</a></li>
<li>Can't send StreamingDecryptingKey between threads -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/975">#975</a></li>
<li>Remove cmake dependency for Windows -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/828">#828</a></li>
<li>Building aws-lc-sys under MSVC is brittle -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/780">#780</a></li>
<li>MSBUILD error MSB1009 install.vcxproj does not exist (but
INSTALL.vcxproj does) -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/772">#772</a></li>
<li>Other libraries that rely on AWS LC SYS do not compile properly in a
Windows environment -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/771">#771</a></li>
<li>Support aws-lc-sys on x86_64-unknown-freebsd without cmake -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/766">#766</a></li>
<li>Unable to build w/ rustc_codegen_cranelift compiler backend - <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/537">#537</a></li>
<li>No mips-unknown-linux-musl support -- <a
href="https://redirect.github.com/aws/aws-lc-rs/issues/522">#522</a></li>
</ul>
<h2>Other Merged PRs</h2>
<ul>
<li>Update toml_edit requirement from 0.23.0 to 0.24.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/976">aws/aws-lc-rs#976</a></li>
<li>Some CI jobs only run on pull-requests by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/970">aws/aws-lc-rs#970</a></li>
<li>More robust rustls integ test by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/973">aws/aws-lc-rs#973</a></li>
<li>Simplify build - no more rust_wrapper lib by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/978">aws/aws-lc-rs#978</a></li>
<li>PR feedback + cleanup -- run-rustls-integration.sh by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/979">aws/aws-lc-rs#979</a></li>
<li>Prepare aws-lc-sys v0.36.0 by <a
href="https://github.com/justsmth"><code>@​justsmth</code></a> in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/992">aws/aws-lc-rs#992</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a
href="https://github.com/cstkingkey"><code>@​cstkingkey</code></a> made
their first contribution in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/988">aws/aws-lc-rs#988</a></li>
<li><a href="https://github.com/roobscoob"><code>@​roobscoob</code></a>
made their first contribution in <a
href="https://redirect.github.com/aws/aws-lc-rs/pull/989">aws/aws-lc-rs#989</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/aws/aws-lc-rs/compare/v1.15.2...v1.15.3">https://github.com/aws/aws-lc-rs/compare/v1.15.2...v1.15.3</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/efaf569ec6c3a3a1d427a5101e363a3ee8f52891"><code>efaf569</code></a>
Prepare aws-lc-rs v1.15.3 (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/998">#998</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/4c475059eb9575fc81b6ff7205be38eb47feeeaa"><code>4c47505</code></a>
disable-prebuilt-nasm feature (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/997">#997</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/8aef7a7ef2cfb67d6187b177d5865c601bb98b7a"><code>8aef7a7</code></a>
<code>less_safe_update</code> for Streaming ciphers (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/991">#991</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/d4c164669f3240e379951f4e073f91bc7ed774f0"><code>d4c1646</code></a>
Prepare aws-lc-fips-sys v0.13.11 (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/994">#994</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/9bd808d3bf9f7d65e4ded728b4bf07d3eaf4683d"><code>9bd808d</code></a>
Prepare aws-lc-sys v0.36.0 (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/992">#992</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/63f2243e354e9b33bd077be80ab3287a47643ddc"><code>63f2243</code></a>
Fix path formatting for build flags in cc_builder (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/989">#989</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/607fa7d1f830c7968093e47e7d8619a41057258f"><code>607fa7d</code></a>
Support mips &amp; rustc_codegen_cranelift compiler backend (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/986">#986</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/dbb7d2e77dac0f696a5b59c94bd4571fdc1e1d5d"><code>dbb7d2e</code></a>
Eliminate CMake Requirement (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/911">#911</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/1cec9de4bfbf426e25ca223b20739ada5f72cd11"><code>1cec9de</code></a>
Add support for i686-win7-windows target (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/988">#988</a>)</li>
<li><a
href="https://github.com/aws/aws-lc-rs/commit/e0aa4187a8e00e2ec69dc4efb8a10a824863f586"><code>e0aa418</code></a>
PR feedback + cleanup -- run-rustls-integration.sh (<a
href="https://redirect.github.com/aws/aws-lc-rs/issues/979">#979</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/aws/aws-lc-rs/compare/v1.15.2...v1.15.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=aws-lc-rs&package-manager=cargo&previous-version=1.15.2&new-version=1.15.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Euclid Ye <yezhizhenjiakang@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Euclid Ye <yezhizhenjiakang@gmail.com>